project_id = "qskmzaxzhkrlchycbria"

[functions.fetch-stripe]
verify_jwt = false

[functions.fetch-paypal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.ses-webhook]
verify_jwt = false
