project_id = "qskmzaxzhkrlchycbria"

[functions.fetch-stripe]
verify_jwt = false

[functions.fetch-paypal]
verify_jwt = false

[functions.fetch-invoices]
verify_jwt = false

[functions.fetch-subscriptions]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.ses-webhook]
verify_jwt = false

[functions.analyze-business]
verify_jwt = false

[functions.sync-clients]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.force-charge-invoice]
verify_jwt = false

[functions.recover-revenue]
verify_jwt = false

[functions.notify-ghl]
verify_jwt = false
